### ISSUE TITLE
bug with command 

### ISSUE THREAD

**Issue by Toinou18** [Fexcraft/FSMM#2]
Hy,
/fsmm add
/fsmm set
/fsmm sub
I have a probleme with all of this command ,she generate an error 

Couldn't process command: fsmm add toinou18 10
java.lang.ArrayIndexOutOfBoundsException: 1
	at net.fexcraft.mod.lib.util.registry.UCResourceLocation.<init>(UCResourceLocation.java:19) ~[UCResourceLocation.class:?]
	at net.fexcraft.mod.fsmm.util.Command.modify(Command.java:116) ~[Command.class:?]
	at net.fexcraft.mod.fsmm.util.Command.func_184881_a(Command.java:105) ~[Command.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
how I fix it ?
Thanks a lot 
Toinou18

**Comment by Fexcraft** [comment]
`/fsmm <action> <type:name/id> <amount>`
e.g.
`/fsmm set player:Steve 20000`
